"""
Backtest engine: validates signal quality on historical data.

Methodology (bias-controlled):
  - Signal date = filing date + 1 day (point-in-time, no look-ahead)
  - Execution date = signal date + 3 calendar days (realistic fill lag)
  - Benchmark: SPY return over same window
  - Delisted stocks: yfinance returns empty / last price → treated as -50% loss
  - Parameters (threshold=65, cluster_window=14d) set from literature, not tuned

Run weekly via GitHub Actions (scripts/run_backtest.py).
"""

import json
import statistics
import time
from datetime import date, timedelta
from typing import List, Dict, Optional

from src.db.connection import get_conn
from src.market.prices import get_price_change_pct
from src.ingest.common import log, phase, fmt_elapsed


HORIZONS = [30, 60, 90, 180]
SPY_TICKER = "SPY"
EXEC_LAG_DAYS = 3  # realistic fill lag after signal date


def run_backtest(threshold: int = 65, lookback_days: int = 365) -> List[Dict]:
    """
    Evaluate all BUY/CLUSTER_BUY signals in the last `lookback_days` days.
    Returns one result dict per horizon (only horizons with completed exits).
    """
    t_start = time.time()
    today = date.today()
    since = today - timedelta(days=lookback_days)

    phase("SIGNAL FETCH")
    log(f"Config: threshold={threshold}, lookback={lookback_days}d, horizons={HORIZONS}")
    log(f"Signal window: {since} → {today}")

    signals = _get_historical_signals(since, threshold)
    log(f"Signals in DB: {len(signals)}")

    if not signals:
        log("  No BUY/CLUSTER_BUY signals found for this window.")
        log("  Signals are generated by daily ingest — run it first, then wait")
        log(f"  {min(HORIZONS) + EXEC_LAG_DAYS}+ days for the shortest ({min(HORIZONS)}d) horizon to have completed exits.")
        return []

    # Breakdown by type and date range
    by_type: Dict[str, int] = {}
    for s in signals:
        by_type[s["signal_type"]] = by_type.get(s["signal_type"], 0) + 1
    log("  " + "  ".join(f"{t}={n}" for t, n in sorted(by_type.items())))

    sig_dates = [_parse_date(s["signal_date"]) for s in signals if _parse_date(s["signal_date"])]
    oldest = min(sig_dates)
    newest = max(sig_dates)
    log(f"  Date range: {oldest} → {newest}  ({(today - oldest).days} days ago → {(today - newest).days} days ago)")

    # Check if any signals are old enough for the shortest horizon
    min_age = min(HORIZONS) + EXEC_LAG_DAYS
    first_completable_cutoff = today - timedelta(days=min_age)
    any_eligible = any(_parse_date(s["signal_date"]) <= first_completable_cutoff for s in signals)
    if not any_eligible:
        first_results_date = oldest + timedelta(days=min_age + 1)
        log(f"  All {len(signals)} signals too recent — need signal_date ≤ {first_completable_cutoff}")
        log(f"  First {min(HORIZONS)}d results available after {first_results_date} "
            f"({(first_results_date - today).days} days from now)")
        log(f"  Nothing to save.")
        return []

    results = []

    for horizon in HORIZONS:
        phase(f"HORIZON {horizon}d")
        t0 = time.time()

        cutoff = today - timedelta(days=horizon + EXEC_LAG_DAYS)
        eligible = [s for s in signals if _parse_date(s["signal_date"]) <= cutoff]
        n_skipped = len(signals) - len(eligible)

        log(f"  {len(eligible)} eligible  ({n_skipped} too recent — need signal_date ≤ {cutoff})")
        if not eligible:
            log("  Skipping horizon — no completed exits yet.")
            continue

        returns = []
        n_no_spy = 0

        for sig in eligible:
            sig_date = _parse_date(sig["signal_date"])
            exec_date = sig_date + timedelta(days=EXEC_LAG_DAYS)
            exit_date = exec_date + timedelta(days=horizon)
            ticker = sig["ticker"]

            ticker_ret = get_price_change_pct(ticker, exec_date, exit_date)
            spy_ret    = get_price_change_pct(SPY_TICKER, exec_date, exit_date)

            if spy_ret is None:
                n_no_spy += 1
                log(f"    {ticker:<6}  SPY data unavailable for {exec_date}→{exit_date} — skipped")
                continue

            if ticker_ret is None:
                ticker_ret = -50.0  # delisted → survivorship bias correction

            excess = ticker_ret - spy_ret
            icon = "✓" if excess > 0 else "✗"
            log(f"    {icon} {ticker:<6}  {sig['signal_type']:<12}  score={sig['score']:>3}  "
                f"exec={exec_date}  tkr={ticker_ret:>+6.1f}%  spy={spy_ret:>+6.1f}%  excess={excess:>+6.1f}%")

            returns.append({
                "ticker": ticker,
                "signal_type": sig["signal_type"],
                "score": sig["score"],
                "exec_date": exec_date.isoformat(),
                "ticker_return": round(ticker_ret, 2),
                "spy_return": round(spy_ret, 2),
                "excess_return": round(excess, 2),
            })

        if not returns:
            log(f"  No valid returns (SPY data missing for all) — skipping horizon.")
            continue

        n = len(returns)
        hit_rate = sum(1 for r in returns if r["excess_return"] > 0) / n * 100
        avg_return = sum(r["excess_return"] for r in returns) / n
        excess_vals = [r["excess_return"] for r in returns]
        if len(excess_vals) > 1 and statistics.stdev(excess_vals) > 0:
            sharpe = (avg_return / statistics.stdev(excess_vals)) * (252 / horizon) ** 0.5
        else:
            sharpe = None

        elapsed_h = time.time() - t0
        log(f"  ── {horizon}d summary ({fmt_elapsed(elapsed_h)}) ──")
        log(f"  Trades={n}  hit={hit_rate:.0f}%  avg_excess={avg_return:+.1f}%  "
            f"sharpe={f'{sharpe:.2f}' if sharpe else 'N/A'}  no_spy_data={n_no_spy}")

        best  = max(returns, key=lambda r: r["excess_return"])
        worst = min(returns, key=lambda r: r["excess_return"])
        log(f"  Best:  {best['ticker']:<6} {best['excess_return']:>+.1f}% excess  ({best['exec_date']})")
        log(f"  Worst: {worst['ticker']:<6} {worst['excess_return']:>+.1f}% excess  ({worst['exec_date']})")

        results.append({
            "horizon_days": horizon,
            "n_trades": n,
            "hit_rate": round(hit_rate, 1),
            "avg_return": round(avg_return, 2),
            "sharpe": round(sharpe, 2) if sharpe is not None else None,
            "detail": returns[:50],
        })

    phase("RESULTS SUMMARY")
    if not results:
        log("No horizons produced results — all exits still in the future.")
    else:
        log(f"{'Horizon':>7}  {'Trades':>6}  {'Hit%':>5}  {'AvgExcess':>9}  {'Sharpe':>6}")
        log("─" * 42)
        for r in results:
            sharpe_str = f"{r['sharpe']:>6.2f}" if r["sharpe"] is not None else "   N/A"
            log(f"  {r['horizon_days']:>4}d  {r['n_trades']:>6}  {r['hit_rate']:>4.0f}%"
                f"  {r['avg_return']:>+8.1f}%  {sharpe_str}")

    log(f"Backtest complete in {fmt_elapsed(time.time() - t_start)}")
    return results


def save_backtest_results(results: List[Dict], threshold: int) -> None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            for r in results:
                cur.execute(
                    """
                    INSERT INTO backtest_runs
                        (run_date, threshold, horizon_days, n_trades, hit_rate, avg_return, sharpe, metrics)
                    VALUES (NOW()::DATE, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        threshold,
                        r["horizon_days"],
                        r["n_trades"],
                        r["hit_rate"],
                        r["avg_return"],
                        r["sharpe"],
                        json.dumps(r.get("detail", [])),
                    ),
                )
    log(f"Saved {len(results)} horizon result(s) to backtest_runs.")


def _get_historical_signals(since: date, threshold: int) -> List[Dict]:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT ticker, signal_date, score, signal_type, cluster_flag
                FROM signals
                WHERE signal_date >= %s
                  AND (score >= %s OR cluster_flag = TRUE)
                  AND signal_type IN ('BUY', 'CLUSTER_BUY')
                ORDER BY signal_date
                """,
                (since, threshold),
            )
            rows = cur.fetchall()
    return [
        dict(zip(["ticker", "signal_date", "score", "signal_type", "cluster_flag"], r))
        for r in rows
    ]


def _parse_date(val) -> Optional[date]:
    if val is None:
        return None
    if isinstance(val, date):
        return val
    try:
        return date.fromisoformat(str(val)[:10])
    except (ValueError, TypeError):
        return None
